name: flutter_learn
description: "Flutter 学习工程 - 对标 SwiftUI 学习工程"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 网络请求
  dio: ^5.4.0

  # 状态管理
  provider: ^6.1.0

  # 本地存储
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0

  # 数据库
  path: ^1.9.0
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 图片
  cached_network_image: ^3.3.0
  image_picker: ^1.0.0

  # 图表
  fl_chart: ^0.68.0

  # 分享
  share_plus: ^9.0.0

  # 地图
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
